---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 0000-argocd-role-binding-admin.yaml
- 0090-sync-cluster-setup.yaml
#- 0100-sync-install-olm.yaml
#- 0100-sync-install-platform.yaml
#- 0100-sync-install-zen-workaround.yaml
#- 0401-postsync-certificates.yaml