apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-cp4d-dummy
  namespace: openshift-gitops
data:
  components: cpd_platform,wkc
  stg_class_block: ocs-storagecluster-ceph-rbd
  stg_class_file: ocs-storagecluster-cephfs
  version: 4.8.2