# This is not actually used by CP4D.
#
# Argo will not perform a synchronization cycle
# without an actual resource in the repository and
# certain combinations of configuration values may
# exclude all other resources in the folder.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-cp4d-dummy
  namespace: cp4dinst01
data:
  components: cpd_platform
  stg_class_block: ocs-storagecluster-ceph-rbd
  stg_class_file: ocs-storagecluster-cephfs
  version: 4.8.2
