---
# Source: databand/templates/deployment-celery-worker-notification.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: databand-celery-w-notif
  labels:
    app: databand
    component: celery-w-notif
    baseComponent: databand-webserver
    chart: databand-1.0.59-4
    release: databand
    heritage: Helm
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    # Smooth rolling update of the celery-w-notif service
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: databand
      component: celery-w-notif
      release: databand
  template:
    metadata:
      annotations:
        checksum/config-env: 3109c2a9a50dcf23eb23cd5b7154adb3449d16cbcda947dbcbe23ae8556ea817
        prometheus.io/port: "8095"
        prometheus.io/scrape: "true"
      labels:
        app: databand
        component: celery-w-notif
        baseComponent: databand-webserver
        release: databand
    spec:
      imagePullSecrets:
        - name: regcred.gitlab.databand
      restartPolicy: Always
      containers:
        - name: databand-celery-w-notif
          image: image-registry.openshift-image-registry.svc:5000/databand/dbnd-webserver:python-v1.0.59.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: "databand-env"
          env:          
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 800m
              memory: 1Gi
          volumeMounts:
            - name: dbnd-prom
              mountPath: /dbnd/prom
            - name: var-tmp
              mountPath: /var/tmp
          args:
            - "bash"
            - "-c"
            - echo 'wait for DB to pass validation...' && dbnd-web db --wait validate --wait-until-pass --timeout-until-pass 3600 && echo "executing  dbnd-web celery worker --concurrency 4 --queues 'notifications' --pool threads..." && dbnd-web celery worker --concurrency 4 --queues 'notifications' --pool threads
          ports:
            - name: celery-w-notif
              containerPort: 8095
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - 'dbnd-web celery inspect ping -d celery@$HOSTNAME'
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: dbnd-prom
          emptyDir: {}
        - name: var-tmp
          emptyDir: {}
