apiVersion: batch/v1
kind: Job
metadata:
  name: sync-cp4d-install-olm
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: install-olm
          image: "icr.io/cpopen/cpd/olm-utils-v2:4.8.3"
          env:
            - name: PROJECT_CPD_INST_OPERATORS
              value: cp4denv01-oper
            - name: PROJECT_CPD_INST_OPERANDS
              value: cp4denv01-inst
            - name: STG_CLASS_BLOCK
              value: ocs-storagecluster-ceph-rbd
            - name: VERSION
              value: 4.8.3
            - name: COMPONENTS
              value: "cpd_platform"
            - name: CPD_CLI_MANAGE_WORKSPACE
              value: /tmp