---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4denv02
  namespace: cp4d-02
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/project
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  source:
    helm:
      parameters:
        - name: components
          value: "none"
        - name:   
    path: ../../cloudpaks/cp4denvs
    repoURL:  "https://github.com/CPDWim/euNTT/"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
