apiVersion: v1
kind: ConfigMap
metadata:
  name: cp4denv01
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
data:
  operator_namespace: cp4denv01-oper
  operand_namespace: cp4denv01-inst
  components: cpd_platform,wkc,datastage
  stg_class_block: ocs-storagecluster-ceph-rbd
  stg_class_file: ocs-storagecluster-cephfs
  version: 4.8.3