---
# Source: databand/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: databand-redis
  namespace: "databand-system"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.3.16
    app.kubernetes.io/instance: databand
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "c2VjcmV0"
