apiVersion: v1
kind: ConfigMap
metadata:
  name: olm-utils-cm
  namespace: crrs-oper
  labels:
    app.kubernetes.io/name: olm-utils
data:
  release_version: 4.8.5
  release_components_meta: |-
    analyticsengine:
        case_version: 8.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    bigsql:
        case_version: 10.5.0
        cr_version: 7.6.5
        csv_version: 10.5.0
        sub_channel: v10.5
    canvasbase:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    ccs:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    cognos_analytics:
        case_version: 25.4.0
        cr_version: 25.4.0
        csv_version: 25.4.0
        sub_channel: v25.4
    cpd_platform:
        case_version: 4.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    cpfs:
        case_version: 4.6.0
        csv_version: 4.6.0
        sub_channel: v4.6
    dashboard:
        case_version: 2.3.0
        cr_version: 4.8.4
        csv_version: 2.3.0
        sub_channel: v2.3
    data_governor:
        case_version: 4.5.4
        csv_version: 4.5.4
        sub_channel: v4.5
    datagate:
        case_version: 7.2.0
        cr_version: 5.2.0
        csv_version: 5.2.0
        sub_channel: v5.2
    datarefinery:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    datastage_ent:
        case_version: 7.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    datastage_ent_plus:
        case_version: 7.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    db2aaservice:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 5.3.0
        sub_channel: v5.3
    db2oltp:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 5.3.0
        sub_channel: v5.3
    db2u:
        case_version: 5.6.4
        csv_version: 5.3.0
        multi_arch_images: cpopen/db2u-operator,cpopen/db2u-day2-operator
        sub_channel: v5.3
    db2wh:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 5.3.0
        sub_channel: v5.3
    dfo:
        case_version: 1.0.0
        cr_version: 1.0.0
        csv_version: 1.0.0
        sub_channel: beta
    dmc:
        case_version: 7.3.0
        cr_version: 4.8.5
        csv_version: 4.3.0
        sub_channel: v4.3
    dods:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    dp:
        case_version: 8.5.0
        cr_version: 4.8.5
        csv_version: 8.5.0
        sub_channel: v8.5
    dpra:
        case_version: 1.14.0
        cr_version: 1.14.0
        csv_version: 1.14.0
        sub_channel: v1.14
    dv:
        case_version: 4.5.0
        cr_version: 2.2.5
        csv_version: 4.5.0
        sub_channel: v4.5
    edb_cp4d:
        case_version: 4.23.0
        cr_version: 4.23.0
        csv_version: 4.23.0
        sub_channel: v4.23
    estap:
        case_version: 1.1.0
        cr_version: 1.1.0
        csv_version: 1.1.0
        sub_channel: v1.1
    factsheet:
        case_version: 3.5.0
        cr_version: 4.8.5
        csv_version: 3.5.0
        sub_channel: v3.5
    fdb_k8s:
        csv_version: 3.1.9
        sub_channel: v3.1
    hee:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 4.85.0
        sub_channel: v4.85
    ibm-cert-manager:
        case_version: 4.2.3
        csv_version: 4.2.3
        sub_channel: v4.2
    ibm-licensing:
        case_version: 4.2.3
        csv_version: 4.2.3
        sub_channel: v4.2
    ibm_events_operator:
        case_version: 5.0.0
        csv_version: 5.0.0
        sub_channel: v3
    ibm_redis_cp:
        case_version: 1.1.8
        csv_version: 1.1.8
        sub_channel: v1.1
    informix:
        case_version: 7.3.0
        csv_version: 7.3.0
        sub_channel: v7.3
    informix_cp4d:
        case_version: 7.3.0
        cr_version: 7.3.0
        csv_version: 7.3.0
        sub_channel: v7.3
    mantaflow:
        case_version: 1.20.0
        cr_version: 42.4.3
        csv_version: 1.20.0
        sub_channel: v1.20
    match360:
        case_version: 3.6.0
        cr_version: 3.6.11
        csv_version: 3.6.0
        sub_channel: v3.6
    model_train:
        case_version: 1.2.14
        csv_version: 2.0.0
        sub_channel: v2.0
    mongodb:
        case_version: 4.22.0
        csv_version: 1.24.0
        sub_channel: stable
    mongodb_cp4d:
        case_version: 4.22.0
        cr_version: 4.22.0
        csv_version: 4.22.0
        sub_channel: v4.22
    opencontent_auditwebhook:
        case_version: 1.0.24
        csv_version: 0.3.1
    opencontent_elasticsearch:
        case_version: 1.1.2071
        cr_version: 1.1.2071
        csv_version: 1.1.2071
        sub_channel: v1.1
    opencontent_etcd:
        case_version: 2.0.35
        csv_version: 1.0.26
    opencontent_fdb:
        case_version: 3.1.9
        cr_version: 3.1.9
        csv_version: 3.1.9
        sub_channel: v3.1
    opencontent_minio:
        case_version: 1.0.23
        csv_version: 1.0.18
    opencontent_rabbitmq:
        case_version: 1.0.35
        csv_version: 1.0.26
        sub_channel: v1.0
    opencontent_redis:
        case_version: 1.6.11
        csv_version: 1.6.11
        sub_channel: v1.6
    openpages:
        case_version: 6.2.0
        cr_version: 9.002.0
        csv_version: 6.2.0
        sub_channel: v6.2
    openpages_instance:
        cr_version: 9.002.0
    openscale:
        case_version: 6.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    planning_analytics:
        case_version: 4.8.4
        cr_version: 4.8.4
        csv_version: 4.8.4
        sub_channel: v7.3
    postgresql:
        case_version: 4.22.0
        csv_version: 1.18.10
        sub_channel: stable
    productmaster:
        case_version: 5.4.0
        cr_version: 5.4.0
        csv_version: 5.4.0
        sub_channel: v5.4
    productmaster_instance:
        cr_version: 5.4.0
    replication:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 3.5.0
        licenses_urls:
            IDRC: https://ibm.biz/BdSZ39
            IDRM: https://ibm.biz/BdSZ33
            IIDRC: https://ibm.biz/BdSZ3C
            IIDRM: https://ibm.biz/BdSZ3T
        sub_channel: v3.5
    rstudio:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    scheduler:
        case_version: 1.22.0
        cr_version: 1.22.0
        csv_version: 1.22.0
        sub_channel: v1.22
    spss:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    syntheticdata:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        licenses_urls:
            WX: https://ibm.biz/Bdv9eP
        sub_channel: v8.5
    voice_gateway:
        case_version: 1.3.8
        cr_version: 1.3.8
        csv_version: 1.3.8
        sub_channel: v1.38
    watson_assistant:
        case_version: 4.25.0
        cr_version: 4.8.5
        csv_version: 4.25.0
        sub_channel: v4.25
    watson_discovery:
        case_version: 7.5.0
        cr_version: 4.8.5
        csv_version: 7.5.0
        sub_channel: v7.5
    watson_gateway:
        case_version: 2.0.31
        csv_version: 1.0.26
    watson_speech:
        case_version: 7.5.0
        cr_version: 4.8.5
        csv_version: 7.5.0
        sub_channel: v7.5
    watsonx_ai:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        licenses_urls:
            WX: https://ibm.biz/Bdv9eP
        sub_channel: v8.5
    watsonx_ai_ifm:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        licenses_urls:
            WX: https://ibm.biz/Bdv9eP
        sub_channel: v8.5
    watsonx_data:
        case_version: 2.4.0
        component_dependencies:
        - analyticsengine
        cr_version: 1.1.4
        csv_version: 2.4.0
        licenses_urls:
            WX: https://ibm.biz/BdmRMr
        sub_channel: v2.4
    watsonx_governance:
        case_version: 1.5.0
        cr_version: 1.1.5
        csv_version: 1.5.0
        sub_channel: v1.5
    watsonx_orchestrate:
        case_version: 1.1.0
        cr_version: 1.1.0
        csv_version: 1.1.0
        sub_channel: v1.1
    wkc:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 1.8.5
        sub_channel: v5.5
    wml:
        case_version: 8.5.0
        cr_version: 4.8.5
        csv_version: 5.5.0
        default_image_groups:
        - ibmwmlRuntimes231
        sub_channel: v5.5
    wml_accelerator:
        case_version: 4.8.5
        cr_version: 4.8.5
        csv_version: 5.5.0
        sub_channel: v5.5
    ws:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        sub_channel: v8.5
    ws_pipelines:
        case_version: 8.5.0
        cr_version: 4.8.5
        csv_version: 8.5.0
        sub_channel: v8.5
    ws_runtimes:
        case_version: 8.5.0
        cr_version: 8.5.0
        csv_version: 8.5.0
        default_image_groups:
        - ibmwsRuntimes231
        sub_channel: v8.5
    wxd_optimizerplus:
        component_dependencies:
        - db2u
    wxo_apicatalog:
        case_version: 1.1.0
        csv_version: 1.5.50
        sub_channel: v3.0
    wxo_components:
        case_version: 1.1.0
        csv_version: 1.1.0
        sub_channel: v1.1
    wxo_digital_employee:
        case_version: 1.1.0
        csv_version: 1.0.0
        sub_channel: v1.0
    zen:
        cr_version: 5.1.3
        csv_version: 5.1.3