apiVersion: batch/v1
kind: Job
metadata:
  name: sync-cp4d-install-zen-workaround
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: patch-zen-database
          image: "icr.io/cpopen/cpd/olm-utils-v2:4.8.2"
          env:
            - name: PROJECT_CPD_INST_OPERATORS
              value: cp4denv01-oper
            - name: PROJECT_CPD_INST_OPERANDS
              value: cp4denv01-isnt
            - name: STG_CLASS_BLOCK
              value: ocs-storagecluster-ceph-rbd
            - name: VERSION
              value: 4.8.2
            - name: COMPONENTS
              value: "cpd_platfrom"
            - name: CPD_CLI_MANAGE_WORKSPACE
              value: /tmp