{{ if not ( eq ( default "" .Values.metadata.operators_namespace ) "ibm-cloudpaks" ) }}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{.Values.metadata.operators_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
