---
# Source: databand/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: databand-postgresql
  namespace: "databand-system"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.6.2
    app.kubernetes.io/instance: databand
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "ZGF0YWJhbmQ="
  password: "ZGF0YWJhbmQ="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
