---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 0000-argocd-role-binding-admin.yaml
#- 0000-image-content-source.yaml
- 0090-sync-cluster-setup.yaml
- 0095-cpd-pidslimit.yaml
#- 0100-sync-install-olm.yaml
- 0101-sync-install-platform.yaml
#- 0102-sync-install-components.yaml
#- 0103-sync-install-manta.yaml
#- 0100-sync-install-zen-workaround.yaml
#- 0401-postsync-certificates.yaml